name: Push to PyPI

on:
  release:
    types: [released, prereleased]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install poetry
      uses: Gr1N/setup-poetry@v4
    - name: Build
      run: |
        poetry version ${{ github.ref }}
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1.6
      with:
        pypi_token: ${{ secrets.pypi_password_sx_did_lib }}
